---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal-app
    spec:
      containers:
      - image: dochonze/portal:latest
        name: portal
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 5000